<?php

namespace Repositories;

/**
 * TypeBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeBookRepository extends \Doctrine\ORM\EntityRepository
{
	    public function getAll()
    {
        return $this->getEntitymanager()->createQueryBuilder()
            ->select('p')
            ->from('Entity\Book', 'p')
            ->orderBy('p.name', 'DESC')
            ->getQuery()
            ->getArrayResult();
    }
}
